### ISSUE TITLE
Compilation errors on Presto .127+

### ISSUE THREAD

**Issue by youngwookim** [qubole/presto-udfs#2]
I got the following errors while I was trying to build with Presto 0.127:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/skt1110551/workspace/presto-udfs/src/main/java/com/facebook/presto/qubole/udfs/UdfFactory.java:[19,36] cannot find symbol
  symbol:   class ParametricFunction
  location: package com.facebook.presto.metadata
[ERROR] /Users/skt1110551/workspace/presto-udfs/src/main/java/com/facebook/presto/qubole/udfs/UdfFactory.java:[20,36] cannot find symbol
  symbol:   class ParametricAggregation
  location: package com.facebook.presto.metadata
[ERROR] /Users/skt1110551/workspace/presto-udfs/src/main/java/com/facebook/presto/qubole/udfs/UdfFactory.java:[49,17] cannot find symbol
  symbol:   class ParametricFunction
  location: class com.facebook.presto.qubole.udfs.UdfFactory
[ERROR] /Users/skt1110551/workspace/presto-udfs/src/main/java/com/facebook/presto/qubole/udfs/UdfFactory.java:[68,17] cannot find symbol
  symbol:   class ParametricAggregation
  location: class com.facebook.presto.qubole.udfs.UdfFactory
[ERROR] /Users/skt1110551/workspace/presto-udfs/src/main/java/com/facebook/presto/qubole/udfs/UdfFactory.java:[70,39] cannot find symbol
  symbol:   class ParametricAggregation
  location: class com.facebook.presto.qubole.udfs.UdfFactory
[INFO] 5 errors
```

**Comment by gitriver** [comment]
not compatible with 0.148
class   at below not found
com.facebook.presto.metadata.ParametricFunction
com.facebook.presto.metadata.ParametricAggregation;
com.facebook.presto.metadata.FunctionInfo;
com.facebook.presto.byteCode.DynamicClassLoader;

**Comment by apoorv2711** [comment]
We have updated the Presto-UDFs to support Presto 0.142. Please try building it again.
